remote_theme: pmarsceill/just-the-docs

title: SBB Cargo API for Measurement Value Acquisition for Wagons
description: Template for documentation of SBB APIs
baseurl: "/api-wagon-maintenance"
url: "https://sbb-api.github.io"

permalink: pretty
search_enabled: true
heading_anchors: true
aux_links:
    " SBB Cargo API for Measurement Value Acquisition for Wagons":
      - "//github.com/sbb-api/api-wagon-maintenance"
